---
- hosts: all
#  sudo: yes
  become: no
  become_method: sudo
  tasks:
  - name: check alive servers
    ping:
  - name: install some stuff
    apt: name=tree state=present
  - name: Create a new file
    file: path=/tmp/foo.conf state=touch
