---
- hosts: all
  sudo: yes
#  become: yes
#  become_method: sudo
  tasks:
  - name: check alive servers
    ping: 127.0.0.1
  - name: install some stuff
    apt: name=tree state=present
  - name: Create a new file
    file: path=/tmp/foo.conf state=touch
